### ISSUE TITLE
Feature Request - Timeout for wait_for_certificate_issued

### ISSUE THREAD

**Issue by vikas027** [cloudposse/terraform-aws-acm-request-certificate#47]
## Describe the Feature

As of now if one set  `wait_for_certificate_issued`  to `true`, terraform waits forever. It would be good to have some timeout defined.

## Describe Ideal Solution

Maybe we can have some timeouts defined in a variable like below and configure it.

```hcl
wait_for_certificate_issued_timeout: "10m"
```

## Alternatives Considered
None as of now, I had to hit Ctrl + C and re-run the terraform job with `wait_for_certificate_issued` as `false`.

**Comment by nitrocode** [comment]
@vikas027 unfortunately this cannot be supported because the `wait_for_certificate_issued` is a toggle on the `aws_acm_certificate_validation` resource which does not support a timeout.

https://github.com/cloudposse/terraform-aws-acm-request-certificate/blob/761030e717ae7297ad134455142e511c57532c9c/main.tf#L45-L49

Ref
* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/acm_certificate_validation
* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/acm_certificate
